# 1. 빌드
FROM gradle:8.10.0-jdk21 AS builder
WORKDIR /home/gradle/src
COPY . .
RUN gradle clean bootJar --no-daemon

# 2. 실행
FROM openjdk:21-jdk-slim
WORKDIR /app
COPY --from=builder /home/gradle/src/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]